// This file will be auto-generated by Supabase CLI after schema is applied
// For now, we use placeholder types that match our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole = 'admin' | 'manager' | 'staff'
export type OrderStatus = 'draft' | 'confirmed' | 'shipped' | 'completed' | 'canceled'
export type InvoiceStatus = 'draft' | 'issued' | 'paid' | 'void'
export type ShipmentStatus = 'pending' | 'in_transit' | 'delivered'

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          name: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          created_at?: string
          updated_at?: string
        }
      }
      profiles: {
        Row: {
          id: string
          tenant_id: string | null
          full_name: string | null
          role: UserRole
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          tenant_id?: string | null
          full_name?: string | null
          role?: UserRole
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string | null
          full_name?: string | null
          role?: UserRole
          created_at?: string
          updated_at?: string
        }
      }
      customers: {
        Row: {
          id: string
          tenant_id: string
          name: string
          email: string | null
          phone: string | null
          address: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          name: string
          email?: string | null
          phone?: string | null
          address?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          name?: string
          email?: string | null
          phone?: string | null
          address?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      products: {
        Row: {
          id: string
          tenant_id: string
          sku: string
          name: string
          description: string | null
          unit: string
          price: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          sku: string
          name: string
          description?: string | null
          unit?: string
          price?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          sku?: string
          name?: string
          description?: string | null
          unit?: string
          price?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      orders: {
        Row: {
          id: string
          tenant_id: string
          customer_id: string
          order_number: string | null
          status: OrderStatus
          order_date: string
          total_amount: number
          notes: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          customer_id: string
          order_number?: string | null
          status?: OrderStatus
          order_date?: string
          total_amount?: number
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          customer_id?: string
          order_number?: string | null
          status?: OrderStatus
          order_date?: string
          total_amount?: number
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          product_id: string
          quantity: number
          unit_price: number
          line_total: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          product_id: string
          quantity?: number
          unit_price: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          product_id?: string
          quantity?: number
          unit_price?: number
          created_at?: string
          updated_at?: string
        }
      }
      invoices: {
        Row: {
          id: string
          tenant_id: string
          order_id: string | null
          invoice_number: string
          status: InvoiceStatus
          issue_date: string | null
          due_date: string | null
          total_amount: number
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          order_id?: string | null
          invoice_number: string
          status?: InvoiceStatus
          issue_date?: string | null
          due_date?: string | null
          total_amount?: number
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          order_id?: string | null
          invoice_number?: string
          status?: InvoiceStatus
          issue_date?: string | null
          due_date?: string | null
          total_amount?: number
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      shipments: {
        Row: {
          id: string
          tenant_id: string
          order_id: string
          shipment_number: string | null
          carrier: string | null
          tracking_code: string | null
          status: ShipmentStatus
          shipped_at: string | null
          delivered_at: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          order_id: string
          shipment_number?: string | null
          carrier?: string | null
          tracking_code?: string | null
          status?: ShipmentStatus
          shipped_at?: string | null
          delivered_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          order_id?: string
          shipment_number?: string | null
          carrier?: string | null
          tracking_code?: string | null
          status?: ShipmentStatus
          shipped_at?: string | null
          delivered_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Enums: {
      user_role: UserRole
      order_status: OrderStatus
      invoice_status: InvoiceStatus
      shipment_status: ShipmentStatus
    }
  }
}

