// This file will be auto-generated by Supabase CLI after schema is applied
// For now, we use placeholder types that match our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// Updated roles: admin, guest, staff, customer
export type UserRole = 'admin' | 'guest' | 'staff' | 'customer'
export type OrderStatus = 'draft' | 'confirmed' | 'shipped' | 'completed' | 'canceled'
export type InvoiceStatus = 'draft' | 'issued' | 'paid' | 'void'
export type ShipmentStatus = 'pending' | 'in_transit' | 'delivered'
export type RequestStatus = 'pending' | 'approved' | 'rejected' | 'accepted'
export type NotificationType = 
  | 'tenant_request_submitted'
  | 'tenant_request_approved'
  | 'tenant_request_rejected'
  | 'tenant_created'
  | 'role_updated'
  | 'system'

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          name: string
          is_locked: boolean
          locked_at: string | null
          locked_reason: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          is_locked?: boolean
          locked_at?: string | null
          locked_reason?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          is_locked?: boolean
          locked_at?: string | null
          locked_reason?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      profiles: {
        Row: {
          id: string
          tenant_id: string | null
          full_name: string | null
          role: UserRole
          session_valid_after?: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          tenant_id?: string | null
          full_name?: string | null
          role?: UserRole
          session_valid_after?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string | null
          full_name?: string | null
          role?: UserRole
          session_valid_after?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      system_settings: {
        Row: {
          key: string
          value: Json
          updated_by: string | null
          updated_at: string
        }
        Insert: {
          key: string
          value: Json
          updated_by?: string | null
          updated_at?: string
        }
        Update: {
          key?: string
          value?: Json
          updated_by?: string | null
          updated_at?: string
        }
      }
      tenant_requests: {
        Row: {
          id: string
          user_id: string
          company_name: string
          company_address: string | null
          company_phone: string | null
          company_email: string | null
          business_type: string | null
          description: string | null
          status: RequestStatus
          reviewed_by: string | null
          reviewed_at: string | null
          review_notes: string | null
          tenant_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          company_name: string
          company_address?: string | null
          company_phone?: string | null
          company_email?: string | null
          business_type?: string | null
          description?: string | null
          status?: RequestStatus
          reviewed_by?: string | null
          reviewed_at?: string | null
          review_notes?: string | null
          tenant_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          company_name?: string
          company_address?: string | null
          company_phone?: string | null
          company_email?: string | null
          business_type?: string | null
          description?: string | null
          status?: RequestStatus
          reviewed_by?: string | null
          reviewed_at?: string | null
          review_notes?: string | null
          tenant_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: NotificationType
          title: string
          message: string
          data: Json
          is_read: boolean
          read_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: NotificationType
          title: string
          message: string
          data?: Json
          is_read?: boolean
          read_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: NotificationType
          title?: string
          message?: string
          data?: Json
          is_read?: boolean
          read_at?: string | null
          created_at?: string
        }
      }
      customers: {
        Row: {
          id: string
          tenant_id: string
          name: string
          email: string | null
          phone: string | null
          address: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          name: string
          email?: string | null
          phone?: string | null
          address?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          name?: string
          email?: string | null
          phone?: string | null
          address?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      products: {
        Row: {
          id: string
          tenant_id: string
          sku: string
          name: string
          description: string | null
          unit: string
          price: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          sku: string
          name: string
          description?: string | null
          unit?: string
          price?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          sku?: string
          name?: string
          description?: string | null
          unit?: string
          price?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      orders: {
        Row: {
          id: string
          tenant_id: string
          customer_id: string
          order_number: string | null
          status: OrderStatus
          order_date: string
          total_amount: number
          notes: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          customer_id: string
          order_number?: string | null
          status?: OrderStatus
          order_date?: string
          total_amount?: number
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          customer_id?: string
          order_number?: string | null
          status?: OrderStatus
          order_date?: string
          total_amount?: number
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          product_id: string
          quantity: number
          unit_price: number
          line_total: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          product_id: string
          quantity?: number
          unit_price: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          product_id?: string
          quantity?: number
          unit_price?: number
          created_at?: string
          updated_at?: string
        }
      }
      invoices: {
        Row: {
          id: string
          tenant_id: string
          order_id: string | null
          invoice_number: string
          status: InvoiceStatus
          issue_date: string | null
          due_date: string | null
          total_amount: number
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          order_id?: string | null
          invoice_number: string
          status?: InvoiceStatus
          issue_date?: string | null
          due_date?: string | null
          total_amount?: number
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          order_id?: string | null
          invoice_number?: string
          status?: InvoiceStatus
          issue_date?: string | null
          due_date?: string | null
          total_amount?: number
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      shipments: {
        Row: {
          id: string
          tenant_id: string
          order_id: string
          shipment_number: string | null
          carrier: string | null
          tracking_code: string | null
          status: ShipmentStatus
          shipped_at: string | null
          delivered_at: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          order_id: string
          shipment_number?: string | null
          carrier?: string | null
          tracking_code?: string | null
          status?: ShipmentStatus
          shipped_at?: string | null
          delivered_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          order_id?: string
          shipment_number?: string | null
          carrier?: string | null
          tracking_code?: string | null
          status?: ShipmentStatus
          shipped_at?: string | null
          delivered_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Enums: {
      user_role: UserRole
      order_status: OrderStatus
      invoice_status: InvoiceStatus
      shipment_status: ShipmentStatus
      request_status: RequestStatus
      notification_type: NotificationType
    }
    Functions: {
      tenant_id: {
        Args: Record<string, never>
        Returns: string
      }
      user_role: {
        Args: Record<string, never>
        Returns: UserRole
      }
      is_admin: {
        Args: Record<string, never>
        Returns: boolean
      }
      get_user_role: {
        Args: Record<string, never>
        Returns: UserRole
      }
      get_unread_notification_count: {
        Args: Record<string, never>
        Returns: number
      }
      approve_tenant_request: {
        Args: { p_request_id: string; p_notes?: string }
        Returns: Json
      }
      reject_tenant_request: {
        Args: { p_request_id: string; p_notes?: string }
        Returns: Json
      }
      accept_approved_request: {
        Args: { p_request_id: string }
        Returns: Json
      }
      toggle_tenant_lock: {
        Args: { p_tenant_id: string; p_is_locked: boolean; p_reason?: string }
        Returns: Json
      }
      mark_notification_read: {
        Args: { p_notification_id: string }
        Returns: boolean
      }
      mark_all_notifications_read: {
        Args: Record<string, never>
        Returns: number
      }
      get_session_config: {
        Args: Record<string, never>
        Returns: Json
      }
      update_session_config: {
        Args: {
          p_timeout_minutes: number
          p_inactivity_minutes?: number
          p_enable_inactivity?: boolean
        }
        Returns: Json
      }
      reset_user_session: {
        Args: { p_user_id: string }
        Returns: Json
      }
      reset_all_sessions: {
        Args: { p_tenant_id?: string }
        Returns: Json
      }
      get_users_admin: {
        Args: Record<string, never>
        Returns: Json
      }
    }
  }
}

// Helper types for easier use
export type Profile = Database['public']['Tables']['profiles']['Row']
export type Tenant = Database['public']['Tables']['tenants']['Row']
export type TenantRequest = Database['public']['Tables']['tenant_requests']['Row']
export type Notification = Database['public']['Tables']['notifications']['Row']
export type Customer = Database['public']['Tables']['customers']['Row']
export type Product = Database['public']['Tables']['products']['Row']
export type Order = Database['public']['Tables']['orders']['Row']
export type OrderItem = Database['public']['Tables']['order_items']['Row']
export type Invoice = Database['public']['Tables']['invoices']['Row']
export type Shipment = Database['public']['Tables']['shipments']['Row']
export type SystemSetting = Database['public']['Tables']['system_settings']['Row']
